RAIRLab/Peirce-My-Heart

.github/workflows/buildAndDeploy.yml
fix deployment issue with wrong build command
=> npm run build

.github/workflows/buildAndDeploy.yml, .github/workflows/validateDocs.yml, .github/workflows/validateHTML.yml, .vscode/settings.json, package-lock.json, package.json, src/index.ts, typedoc.json
I added JSDoc as an NPM package
=> Add TypeDoc support 

.github/workflows/buildAndDeploy.yml
Swapped order of build and build docs to take account of the new doc build process.
=> Update buildAndDeploy.yml, Fix documentation gen bug

src/AtomCreation.ts
This should fix it, please yell at me if it does not
=> Fix Atom Disappearing Bug

src/AtomCreation.ts
It works, let me know if you want me to edit how it handles it. Right now it doesn't react at all and just continues using the last valid letter, I could create some kind of reaction if you want. That little issue with the RegExp type is interesting,
=> Isuse #50 prevent non letters from being selected.

.eslintignore, .vscode/launch.json, .vscode/settings.json, package-lock.json, package.json, src/AEG/AEGTree.ts, src/AEG/AtomNode.ts, src/AEG/CutNode.ts, src/AEG/Ellipse.ts, src/AEG/Rectangle.ts, src/AtomCreation.ts, src/EllipseCreation.ts, src/index.html, src/index.ts
Fixed some middleware bugs: in particular insert.
Added rudimentary collision checking using ellipse bounding boxes.
Added basic colors for cuts when drawing.
Added toString for AEG that prints the text version from the tree state. 
Added text display of tree state.
=> Imperial branch

.vscode/settings.json, src/AEG/Ellipse.ts, src/AEG/Rectangle.ts
check for contains during ellipse overalps, collapsed rectangle overlaps into single function
=> Ellipse collision detection bug

src/AtomMode.ts, src/index.html
Just a quick PR for this little bit so I can click the one checkmark
=> Issue #59 Atom Selected

src/AEG/AEGTree.ts, src/AEG/AEGUtils.ts, src/AEG/AtomNode.ts, src/AEG/CutNode.ts, src/AEG/Ellipse.ts, src/AEG/Rectangle.ts, src/AtomMode.ts, src/CutMode.ts, src/index.ts
Added more points, made changes based on code review for issue 105 divergent overlaps implementation
=> 110 more points on ellipses for collison check

src/AEG/AEGTree.ts
=> no executions on my watch

src/AEG/AtomNode.ts
Master is broke this is a quick patch fix as I do not have time today.
If we do not want default rectangles I can fix things on my end in master.
=> Temporary Master Fix

src/CutMode.ts
It was just the offset that's my bad I forgot about the draw there.
When I make the draw.util file I will rework how this box is drawn.
=> Guideline fix

src/index.ts
Not complete yet, need to work on overriding the html download shortcut for Google, if possible
=> Save shortcut!

src/index.css
Willing to make changes when needed.
=> Changed shape of button/color is blue when hovered

.eslintrc.json, .vscode/settings.json, src/AtomMode.ts, src/CutMode.ts, src/Themes.ts, src/index.css, src/index.html, src/index.ts, src/themes.css
Closes #134 
* Implemented basic support for Changeable Themes
* Added an ignore for that line ending lint error. 
These themes use localStorage to cache the last theme you were using on the site, so you only need to change once.
=> Changeable themes, lint line ending fix

src/about.html, src/aeg.html, src/index.css, src/index.html, src/style.css
Will probably need to add inference rules whenever they spawn into existence. Homepage is pretty empty so I tried to have it look fancy but I'm artistically impaired so please send help
=> homepage and basic about

src/CopySingleMode.ts
I ended up leaving a condition in because I wasn't thinking about it
=> Childless cuts now can be copied again

src/about.html
Changed the equivalent statement
=> logical oops

src/ToggleModes.ts, src/index.css, src/index.html, src/index.ts
Did a pr with the current code. Will make changes as needed.
=> toggle mode from draw to proof mode

src/index.css
padding on tool settings to fix alignment and add needed spacing
=> Fix Checkbox Alignment Issue

src/index.ts
DOMException on closing file picker no longer prints to console
=> DOMException on closing file picker no longer prints to console

src/index.css
thought this would be a nice addition, not sure how much it would actually be used lol
=> vertical scroll on history bar

src/ProofTools/DoubleCutInsertionTool.ts
Created a helper function to handle determining if a double cut is currently in a valid position and a helper function for that to make sure no the outer cut has no additional children except for the inner cut.
=> 374 Double Cut can have different Atoms on both layers!
